### PR TITLE
Improved error messages and allow for error handling in code using the module

### PR DESCRIPTION
**Pull request by mi-hol**
Hi Joakim,
I'd like to use your module but had some issue in handling errors.
1. Tried to improve error messages and allow for error handling in code using the module by using 'throw' instead of 'return'.
2. Please select a license for the repository too
Thanks
Michael

### CODE REVIEW

**Comment by EliteLoser** [comment]
Hi. Yeah, it's a great module, super convenient, I use it myself.

The intended error handling is as follows, by using `-ErrorAction Stop` for Merge-Csv in a try/catch block.

```powershell
> try { 
    Merge-Csv -Path .\csv1.csv, .\csv2.csv, .\csv3.csv `
        -Identity Name -ErrorAction Stop }
catch {
    "Got an error: $_"
}
Got an error: Some headers are shared. Are you just looking for '@(ipcsv csv1) + @(ipcsv csv2) | Export-Csv ...'?
To remove duplicate (between the files to merge) headers from a CSV file, Import-Csv it, pass it to Select-Object, and omit the duplicate header(s)/column(s).
Exiting.
```

The error message does stink a bit. Let me think for a while. :) I'm not contented with yours either. ;)

**Comment by mi-hol** [comment]
Hi Joakim,
thanks for the clarification.
I'm  targeting a production environment operated by cheap IT support.
Hence I'd benefit from short messages indicating clearly errors, warnings and information
The current messages seem (at least partially) targeted at solution developers.I'd be happy to bounce around ideas.

**Comment by mi-hol** [comment]
Hi Joakim, did you perhaps get a chance to think about the error messages yet?

**Comment by EliteLoser** [comment]
Hi. I've added some CmdletBinding boilerplate code I noticed was missing.

The big red letters PowerShell displays by default on errors (such as when I use Write-Error) should help aid them in detecting it's an error. In addition I've altered the text a bit and now also include "Error" as a word. Is this enough? There are limits to how much you can simplify for someone who actually has to use the tool.

```

PS C:\temp\MergeCsv\1.7.1> ipmo .\MergeCsv.psm1 -Force

PS C:\temp\MergeCsv\1.7.1> merge-csv -path (gci c:\temp\csv?.csv | % FullName) -Identity name
merge-csv : Error. Check your input. Some headers are shared aside from the specified ID 
column(s). You could possibly just be looking for '@(Import-Csv csv1) + @(Import-Csv csv2) | 
Export-Csv ... merged.csv'.
To remove duplicate (between the files or objects to merge) headers from a CSV file, possibly 
Import-Csv it, pass it to Select-Object and omit the duplicate header(s)/column(s).
Exiting.
At line:1 char:1
+ merge-csv -path (gci c:\temp\csv?.csv | % FullName) -Identity name
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Merge-Csv
 

PS C:\temp\MergeCsv\1.7.1> merge-csv -path (gci c:\temp\csv?.csv | % FullName) -Identity notaheader
merge-csv : Error. Check your input. Headers in object/file 1 don't include the identity header 
'notaheader'. Exiting.
At line:1 char:1
+ merge-csv -path (gci c:\temp\csv?.csv | % FullName) -Identity notahea ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Merge-Csv
```

I'll await feedback.

Edit: This also has the side effect of making the errors script-terminating by default, which might be to your liking. I hope it doesn't ruin the rest of the population using this module now - I don't expect it to as I expect existing users' `-ErrorAction Stop` in code to in the future simply become unneeded (barring any future changes).

Example:

```powershell
try {
    Merge-Csv -Path (gci c:\temp\csv?.csv | % FullName) -Identity name
} catch { 'Caught error' }

Caught error
```

**Comment by mi-hol** [comment]
Hi Joakim,
adding the keyword 'error' is what I was looking for.
Thank you so much!
In large IT environments log file collectors are used and string matching rules decide about success or failure of a job.
A side effect of log file collectors is that color coding like  'The big red letters PowerShell displays by default on errors (such as when I use Write-Error) should help aid them in detecting it's an error.' is stripped off :(
I'll test the new code within a weeks time and will come back with results.

**Comment by mi-hol** [comment]
re 'the side effect of making the errors script-terminating by default, which might be to your liking. I hope it doesn't ruin the rest of the population using this module now' maybe you wanted to apply 'semantic versioning rules'  as defined on https://semver.org/ . A potentially incompatible change like this would warrant a version 2.0.0 instead of 1.7.1

**Comment by mi-hol** [comment]
Hi Joakim,
apologize didn't get the time to test yet. Will need more time to come back on the change.
Expect an update in second week of Jan2019 only.

**Comment by mi-hol** [comment]
Hi Joakim,
I've started to test and see a minor difference in output for an error case that I'll need to investigate further

**Comment by EliteLoser** [comment]
It's been a year and I haven't heard anything. Closing this.

**Pull request closed without merging**
